theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Columbia Integration Bee]
descrption: Contest Information
author: George Dragomir
email: george.dragomir@columbia.edu
